app:
  port: 8082

db:
  host: 127.0.0.1
  port: 3306
  user: admin
  password: password
  name: order-db
  nameS1: order-db-s1
  nameS2: order-db-s2

secret:
  jwtSecret: "secret"

redis:
  host: 127.0.0.1
  port: 6379
  password: "root"

services:
  product: "http://localhost:8081"
  pricing: "http://localhost:8083"

kafka:
  brokers:
    - "localhost:9092"
    - "localhost:9093"
    - "localhost:9094"
  topic: "order-topic"